apiVersion: apps/v1
kind: Deployment
metadata:
  name: sincronizacion
  namespace: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sincronizacion
  template:
    metadata:
      labels:
        app: sincronizacion
    spec:
      containers:
      - name: sincronizacion
        image: greinoso/sincronizacion:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: microservicios-config
              key: RABBITMQ_HOST
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: microservicios-config
              key: RABBITMQ_USERNAME
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: microservicios-config
              key: RABBITMQ_PASSWORD
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sincronizacion-service
  namespace: microservicios
spec:
  selector:
    app: sincronizacion
  ports:
  - port: 8080
    targetPort: 8080