server:
  port: 0

spring:
  application:
    name: SERVICIO-NOTIFICACIONES
  datasource:
    url: jdbc:postgresql://localhost:26257/dbnotifications?sslmode=disable
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---
# Perfil para Docker/Kubernetes
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: SERVICIO-NOTIFICACIONES
  datasource:
    url: jdbc:postgresql://cockroach-service:26257/dbnotifications?sslmode=disable
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: admin
    password: admin

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:unknown}
    instance-id: ${spring.application.name}:${HOSTNAME:unknown}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always